import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const source = html.match(/    function updateTimelinePresentation\(\) \{[\s\S]*?\n    \}/)[0];
const nodes = Object.fromEntries(['hourSlider','timelineDock','timelineBubble','timelineFirstTime','timelineLastTime'].map(id => [id, {dataset:{}, attrs:{}, style:{setProperty(){}}, setAttribute(k,v){this.attrs[k]=v;}}]));
nodes.timelineBubble.textContent='Oct 9 · 3 AM 2.0 ft';
const context = vm.createContext({document:{getElementById:id=>nodes[id]}, compact:false, currentDataMode:'forecast', currentHourIndex:0, currentSeriesHours:[], isCompactFloodmapperLayout:()=>context.compact, sameEntryESTDay:(a,b)=>a.day===b.day, getTimelineIntervalMinutes:()=>60, formatHourEntryTimeCompact:e=>e.time, buildTimelineGroupGradient:()=>''});
vm.runInContext(source, context);
const series = [{day:'8',time:'11 PM'},{day:'9',time:'12 AM'},{day:'9',time:'1 AM'},{day:'9',time:'2 AM'},{day:'10',time:'12 AM'}];
context.currentSeriesHours=series; context.currentHourIndex=2;
context.updateTimelinePresentation();
assert.deepEqual([nodes.hourSlider.min,nodes.hourSlider.max,nodes.hourSlider.value],['0','4','2']);
context.compact=true; context.updateTimelinePresentation();
assert.deepEqual([nodes.hourSlider.min,nodes.hourSlider.max,nodes.hourSlider.value],['1','3','2']);
assert.equal(nodes.timelineFirstTime.textContent,'12 AM'); assert.equal(nodes.timelineLastTime.textContent,'2 AM');
assert.equal(nodes.hourSlider.disabled,false);
context.currentHourIndex=4; context.updateTimelinePresentation();
assert.equal(nodes.hourSlider.disabled,true); assert.equal(nodes.timelineDock.dataset.singleTimelineTime,'true');
context.currentDataMode='observed'; context.currentSeriesHours=[]; context.currentHourIndex=0; context.updateTimelinePresentation();
assert.equal(nodes.hourSlider.disabled,true); assert.equal(nodes.hourSlider.attrs['aria-label'],'Past flood time');
assert.equal(nodes.timelineFirstTime.textContent,'');
context.compact=false; context.currentSeriesHours=series; context.currentHourIndex=2; context.updateTimelinePresentation();
assert.deepEqual([nodes.hourSlider.min,nodes.hourSlider.max],['0','4']);
assert.equal(context.currentSeriesHours,series); assert.equal(series.length,5);
console.log('PASS responsive timeline: global indices, day boundaries, single crest, empty records, desktop restoration, unchanged series.');
const switchSource=html.match(/    async function switchOverlayMode\(mode\) \{[\s\S]*?\n    \}/)[0];
Object.assign(context,{currentOverlayMode:'depth',currentDataMode:'observed',currentViewType:'observed-day',currentHourIndex:3,stopPlayback(){},toast(){},updateModeButtons(){},renderHour:async index=>assert.equal(index,3)});
vm.runInContext(switchSource,context);
await context.switchOverlayMode('dynamic');
assert.equal(context.currentDataMode,'observed'); assert.equal(context.currentViewType,'observed-day'); assert.equal(context.currentHourIndex,3);
console.log('PASS overlay changes preserve Past date and time.');
